bin:
  directory: "~/bin"

projects:
  directory: "~/Projects"
  subDirectories: true
  startupWindows:
    - nvim:
        command: "nivm ."
  switchCommands:
    - ["ln", "-sfn", "/opt/example/config $(pwd)"]
    - ["ln", "-sfn", "$(pwd)/.nvim.lua ~/Projects/.nvim.lua"]
