defaultProject: projects--dots

projects:
  bin:
    directory: "~/bin"

  projects:
    directory: "~/Projects"
    subDirectories: true
    startupWindows:
      - name: nvim
        command: "nivm ."
      - name: shell
    switchCommands:
      - ["ln", "-sfn", "/opt/example/config $(pwd)"]
      - ["ln", "-sfn", "$(pwd)/.nvim.lua ~/Projects/.nvim.lua"]
