combineProjects: true
fzfFlags:
  - "--ansi"
  - "--bind"
  - "ctrl-k:execute(tmixer kill {2})+reload(tmixer list)"
  - "--bind"
  - "ctrl-r:execute(tmixer reset {2})+reload(tmixer list)"
  - "--bind"
  - "ctrl-s:execute(tmixer start {2})+reload(tmixer list)"
