// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Pid           *int64                 `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *PingResponse) GetPid() int64 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Args
	//	*Request_Selection
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetArgs() *Args {
	if x != nil {
		if x, ok := x.Payload.(*Request_Args); ok {
			return x.Args
		}
	}
	return nil
}

func (x *Request) GetSelection() *Selection {
	if x != nil {
		if x, ok := x.Payload.(*Request_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Args struct {
	Args *Args `protobuf:"bytes,1,opt,name=args,oneof"`
}

type Request_Selection struct {
	Selection *Selection `protobuf:"bytes,2,opt,name=selection,oneof"`
}

func (*Request_Args) isRequest_Payload() {}

func (*Request_Selection) isRequest_Payload() {}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *Args) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *string                `protobuf:"bytes,1,req,name=project" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *Selection) GetProject() string {
	if x != nil && x.Project != nil {
		return *x.Project
	}
	return ""
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_NeedsSelection
	//	*Response_Output
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetNeedsSelection() *NeedsSelection {
	if x != nil {
		if x, ok := x.Payload.(*Response_NeedsSelection); ok {
			return x.NeedsSelection
		}
	}
	return nil
}

func (x *Response) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Payload.(*Response_Output); ok {
			return x.Output
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_NeedsSelection struct {
	NeedsSelection *NeedsSelection `protobuf:"bytes,1,opt,name=needsSelection,oneof"`
}

type Response_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,oneof"`
}

func (*Response_NeedsSelection) isResponse_Payload() {}

func (*Response_Output) isResponse_Payload() {}

type NeedsSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []string               `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedsSelection) Reset() {
	*x = NeedsSelection{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedsSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedsSelection) ProtoMessage() {}

func (x *NeedsSelection) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedsSelection.ProtoReflect.Descriptor instead.
func (*NeedsSelection) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *NeedsSelection) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *string                `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
	Selected      *string                `protobuf:"bytes,2,opt,name=selected" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *Output) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *Output) GetSelected() string {
	if x != nil && x.Selected != nil {
		return *x.Selected
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\"\a\n" +
	"\x05Empty\":\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x02(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x02 \x02(\x03R\x03pid\"]\n" +
	"\aRequest\x12\x1b\n" +
	"\x04args\x18\x01 \x01(\v2\x05.ArgsH\x00R\x04args\x12*\n" +
	"\tselection\x18\x02 \x01(\v2\n" +
	".SelectionH\x00R\tselectionB\t\n" +
	"\apayload\"\x1a\n" +
	"\x04Args\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"%\n" +
	"\tSelection\x12\x18\n" +
	"\aproject\x18\x01 \x02(\tR\aproject\"s\n" +
	"\bResponse\x129\n" +
	"\x0eneedsSelection\x18\x01 \x01(\v2\x0f.NeedsSelectionH\x00R\x0eneedsSelection\x12!\n" +
	"\x06output\x18\x02 \x01(\v2\a.OutputH\x00R\x06outputB\t\n" +
	"\apayload\",\n" +
	"\x0eNeedsSelection\x12\x1a\n" +
	"\bprojects\x18\x01 \x03(\tR\bprojects\"<\n" +
	"\x06Output\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\tR\bselected2g\n" +
	"\x06Tmixer\x12\"\n" +
	"\aSession\x12\b.Request\x1a\t.Response(\x010\x01\x12\x1d\n" +
	"\x04Ping\x12\x06.Empty\x1a\r.PingResponse\x12\x1a\n" +
	"\bShutDown\x12\x06.Empty\x1a\x06.EmptyB\fZ\n" +
	"./protocol"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_proto_goTypes = []any{
	(*Empty)(nil),          // 0: Empty
	(*PingResponse)(nil),   // 1: PingResponse
	(*Request)(nil),        // 2: Request
	(*Args)(nil),           // 3: Args
	(*Selection)(nil),      // 4: Selection
	(*Response)(nil),       // 5: Response
	(*NeedsSelection)(nil), // 6: NeedsSelection
	(*Output)(nil),         // 7: Output
}
var file_service_proto_depIdxs = []int32{
	3, // 0: Request.args:type_name -> Args
	4, // 1: Request.selection:type_name -> Selection
	6, // 2: Response.needsSelection:type_name -> NeedsSelection
	7, // 3: Response.output:type_name -> Output
	2, // 4: Tmixer.Session:input_type -> Request
	0, // 5: Tmixer.Ping:input_type -> Empty
	0, // 6: Tmixer.ShutDown:input_type -> Empty
	5, // 7: Tmixer.Session:output_type -> Response
	1, // 8: Tmixer.Ping:output_type -> PingResponse
	0, // 9: Tmixer.ShutDown:output_type -> Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[2].OneofWrappers = []any{
		(*Request_Args)(nil),
		(*Request_Selection)(nil),
	}
	file_service_proto_msgTypes[5].OneofWrappers = []any{
		(*Response_NeedsSelection)(nil),
		(*Response_Output)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
