// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tmixer_Session_FullMethodName  = "/Tmixer/Session"
	Tmixer_Ping_FullMethodName     = "/Tmixer/Ping"
	Tmixer_ShutDown_FullMethodName = "/Tmixer/ShutDown"
)

// TmixerClient is the client API for Tmixer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TmixerClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	ShutDown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type tmixerClient struct {
	cc grpc.ClientConnInterface
}

func NewTmixerClient(cc grpc.ClientConnInterface) TmixerClient {
	return &tmixerClient{cc}
}

func (c *tmixerClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tmixer_ServiceDesc.Streams[0], Tmixer_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tmixer_SessionClient = grpc.BidiStreamingClient[Request, Response]

func (c *tmixerClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Tmixer_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tmixerClient) ShutDown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Tmixer_ShutDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TmixerServer is the server API for Tmixer service.
// All implementations must embed UnimplementedTmixerServer
// for forward compatibility.
type TmixerServer interface {
	Session(grpc.BidiStreamingServer[Request, Response]) error
	Ping(context.Context, *Empty) (*PingResponse, error)
	ShutDown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedTmixerServer()
}

// UnimplementedTmixerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTmixerServer struct{}

func (UnimplementedTmixerServer) Session(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedTmixerServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTmixerServer) ShutDown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutDown not implemented")
}
func (UnimplementedTmixerServer) mustEmbedUnimplementedTmixerServer() {}
func (UnimplementedTmixerServer) testEmbeddedByValue()                {}

// UnsafeTmixerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TmixerServer will
// result in compilation errors.
type UnsafeTmixerServer interface {
	mustEmbedUnimplementedTmixerServer()
}

func RegisterTmixerServer(s grpc.ServiceRegistrar, srv TmixerServer) {
	// If the following call panics, it indicates UnimplementedTmixerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tmixer_ServiceDesc, srv)
}

func _Tmixer_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TmixerServer).Session(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tmixer_SessionServer = grpc.BidiStreamingServer[Request, Response]

func _Tmixer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TmixerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tmixer_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TmixerServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tmixer_ShutDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TmixerServer).ShutDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tmixer_ShutDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TmixerServer).ShutDown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Tmixer_ServiceDesc is the grpc.ServiceDesc for Tmixer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tmixer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tmixer",
	HandlerType: (*TmixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Tmixer_Ping_Handler,
		},
		{
			MethodName: "ShutDown",
			Handler:    _Tmixer_ShutDown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Tmixer_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
