// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Args
	//	*Request_Selection
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_protocol_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetArgs() *Args {
	if x != nil {
		if x, ok := x.Payload.(*Request_Args); ok {
			return x.Args
		}
	}
	return nil
}

func (x *Request) GetSelection() *Selection {
	if x != nil {
		if x, ok := x.Payload.(*Request_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Args struct {
	Args *Args `protobuf:"bytes,1,opt,name=args,oneof"`
}

type Request_Selection struct {
	Selection *Selection `protobuf:"bytes,2,opt,name=selection,oneof"`
}

func (*Request_Args) isRequest_Payload() {}

func (*Request_Selection) isRequest_Payload() {}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_internal_protocol_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{1}
}

func (x *Args) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *string                `protobuf:"bytes,1,req,name=project" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_internal_protocol_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{2}
}

func (x *Selection) GetProject() string {
	if x != nil && x.Project != nil {
		return *x.Project
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []string               `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_protocol_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_internal_protocol_service_proto protoreflect.FileDescriptor

const file_internal_protocol_service_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/service.proto\"]\n" +
	"\aRequest\x12\x1b\n" +
	"\x04args\x18\x01 \x01(\v2\x05.ArgsH\x00R\x04args\x12*\n" +
	"\tselection\x18\x02 \x01(\v2\n" +
	".SelectionH\x00R\tselectionB\t\n" +
	"\apayload\"\x1a\n" +
	"\x04Args\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"%\n" +
	"\tSelection\x12\x18\n" +
	"\aproject\x18\x01 \x02(\tR\aproject\"<\n" +
	"\bResponse\x12\x1a\n" +
	"\bprojects\x18\x01 \x03(\tR\bprojects\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2,\n" +
	"\x06Tmixer\x12\"\n" +
	"\aSession\x12\b.Request\x1a\t.Response(\x010\x01B\fZ\n" +
	"./protocol"

var (
	file_internal_protocol_service_proto_rawDescOnce sync.Once
	file_internal_protocol_service_proto_rawDescData []byte
)

func file_internal_protocol_service_proto_rawDescGZIP() []byte {
	file_internal_protocol_service_proto_rawDescOnce.Do(func() {
		file_internal_protocol_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_service_proto_rawDesc), len(file_internal_protocol_service_proto_rawDesc)))
	})
	return file_internal_protocol_service_proto_rawDescData
}

var file_internal_protocol_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_protocol_service_proto_goTypes = []any{
	(*Request)(nil),   // 0: Request
	(*Args)(nil),      // 1: Args
	(*Selection)(nil), // 2: Selection
	(*Response)(nil),  // 3: Response
}
var file_internal_protocol_service_proto_depIdxs = []int32{
	1, // 0: Request.args:type_name -> Args
	2, // 1: Request.selection:type_name -> Selection
	0, // 2: Tmixer.Session:input_type -> Request
	3, // 3: Tmixer.Session:output_type -> Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protocol_service_proto_init() }
func file_internal_protocol_service_proto_init() {
	if File_internal_protocol_service_proto != nil {
		return
	}
	file_internal_protocol_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Args)(nil),
		(*Request_Selection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_service_proto_rawDesc), len(file_internal_protocol_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_service_proto_goTypes,
		DependencyIndexes: file_internal_protocol_service_proto_depIdxs,
		MessageInfos:      file_internal_protocol_service_proto_msgTypes,
	}.Build()
	File_internal_protocol_service_proto = out.File
	file_internal_protocol_service_proto_goTypes = nil
	file_internal_protocol_service_proto_depIdxs = nil
}
