// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PROJECT_STATUS_INACTIVE Status = 0
	Status_PROJECT_STATUS_ACTIVE   Status = 1
	Status_PROJECT_STATUS_ATTACHED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PROJECT_STATUS_INACTIVE",
		1: "PROJECT_STATUS_ACTIVE",
		2: "PROJECT_STATUS_ATTACHED",
	}
	Status_value = map[string]int32{
		"PROJECT_STATUS_INACTIVE": 0,
		"PROJECT_STATUS_ACTIVE":   1,
		"PROJECT_STATUS_ATTACHED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_protocol_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Status(num)
	return nil
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Args
	//	*Request_Selection
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_protocol_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetArgs() *Args {
	if x != nil {
		if x, ok := x.Payload.(*Request_Args); ok {
			return x.Args
		}
	}
	return nil
}

func (x *Request) GetSelection() *Selection {
	if x != nil {
		if x, ok := x.Payload.(*Request_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Args struct {
	Args *Args `protobuf:"bytes,1,opt,name=args,oneof"`
}

type Request_Selection struct {
	Selection *Selection `protobuf:"bytes,2,opt,name=selection,oneof"`
}

func (*Request_Args) isRequest_Payload() {}

func (*Request_Selection) isRequest_Payload() {}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_internal_protocol_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{1}
}

func (x *Args) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,req,name=project" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_internal_protocol_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{2}
}

func (x *Selection) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Status        *Status                `protobuf:"varint,2,req,name=status,enum=Status" json:"status,omitempty"`
	LastActivity  *int64                 `protobuf:"varint,3,req,name=lastActivity" json:"lastActivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_internal_protocol_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{3}
}

func (x *Project) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Project) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_PROJECT_STATUS_INACTIVE
}

func (x *Project) GetLastActivity() int64 {
	if x != nil && x.LastActivity != nil {
		return *x.LastActivity
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_protocol_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_protocol_service_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_internal_protocol_service_proto protoreflect.FileDescriptor

const file_internal_protocol_service_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/service.proto\"]\n" +
	"\aRequest\x12\x1b\n" +
	"\x04args\x18\x01 \x01(\v2\x05.ArgsH\x00R\x04args\x12*\n" +
	"\tselection\x18\x02 \x01(\v2\n" +
	".SelectionH\x00R\tselectionB\t\n" +
	"\apayload\"\x1a\n" +
	"\x04Args\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"/\n" +
	"\tSelection\x12\"\n" +
	"\aproject\x18\x01 \x02(\v2\b.ProjectR\aproject\"b\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x1f\n" +
	"\x06status\x18\x02 \x02(\x0e2\a.StatusR\x06status\x12\"\n" +
	"\flastActivity\x18\x03 \x02(\x03R\flastActivity\"F\n" +
	"\bResponse\x12$\n" +
	"\bprojects\x18\x01 \x03(\v2\b.ProjectR\bprojects\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*]\n" +
	"\x06Status\x12\x1b\n" +
	"\x17PROJECT_STATUS_INACTIVE\x10\x00\x12\x19\n" +
	"\x15PROJECT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17PROJECT_STATUS_ATTACHED\x10\x022,\n" +
	"\x06Tmixer\x12\"\n" +
	"\aSession\x12\b.Request\x1a\t.Response(\x010\x01B\fZ\n" +
	"./protocol"

var (
	file_internal_protocol_service_proto_rawDescOnce sync.Once
	file_internal_protocol_service_proto_rawDescData []byte
)

func file_internal_protocol_service_proto_rawDescGZIP() []byte {
	file_internal_protocol_service_proto_rawDescOnce.Do(func() {
		file_internal_protocol_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_service_proto_rawDesc), len(file_internal_protocol_service_proto_rawDesc)))
	})
	return file_internal_protocol_service_proto_rawDescData
}

var file_internal_protocol_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protocol_service_proto_goTypes = []any{
	(Status)(0),       // 0: Status
	(*Request)(nil),   // 1: Request
	(*Args)(nil),      // 2: Args
	(*Selection)(nil), // 3: Selection
	(*Project)(nil),   // 4: Project
	(*Response)(nil),  // 5: Response
}
var file_internal_protocol_service_proto_depIdxs = []int32{
	2, // 0: Request.args:type_name -> Args
	3, // 1: Request.selection:type_name -> Selection
	4, // 2: Selection.project:type_name -> Project
	0, // 3: Project.status:type_name -> Status
	4, // 4: Response.projects:type_name -> Project
	1, // 5: Tmixer.Session:input_type -> Request
	5, // 6: Tmixer.Session:output_type -> Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_protocol_service_proto_init() }
func file_internal_protocol_service_proto_init() {
	if File_internal_protocol_service_proto != nil {
		return
	}
	file_internal_protocol_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Args)(nil),
		(*Request_Selection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_service_proto_rawDesc), len(file_internal_protocol_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_service_proto_goTypes,
		DependencyIndexes: file_internal_protocol_service_proto_depIdxs,
		EnumInfos:         file_internal_protocol_service_proto_enumTypes,
		MessageInfos:      file_internal_protocol_service_proto_msgTypes,
	}.Build()
	File_internal_protocol_service_proto = out.File
	file_internal_protocol_service_proto_goTypes = nil
	file_internal_protocol_service_proto_depIdxs = nil
}
