name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TERM: "xterm-256color"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25.4'

    - name: Check TERM environment variable
      run: echo "TERM is set to $TERM"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y tmux fzf

    - name: Run check
      run: make check

    - name: Run build
      run: make build
