name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tmux
      run: sudo apt-get update && sudo apt-get install -y tmux

    - name: Run check-fmt
      run: make check-fmt

    - name: Run test
      run: make test

    - name: Run build
      run: make build
